import Head from "next/head";
import stylesn from "@/styles/ninja.module.css";
import styles from "@/styles/page.module.css";
import Link from "next/link";

const ninja = ({ ninjas }) => {
  return (
    <>
      <Head>
        <title>Ninja</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className={styles.title}>Ninja Page</h1>
        <div>
          {ninjas?.map((nin) => (
            <div key={nin.id}>
              <Link href={`/ninja/${nin.id}`} className={stylesn.single}>
                <h3>{nin.name}</h3>
              </Link>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default ninja;

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/users");
  const data = await res.json();

  return {
    props: { ninjas: data },
  };
};
